### ISSUE TITLE
Resources containing "aux" should be shown differently

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#105]
This request emerged in the last meeting, but more details are needed.

**Comment by janeuhd** [comment]
@hannaboe I don't think this is an issue. or? Hanna's comment was related to whether aux files should be shown always at the top or bottom in the file list, but I think we agreed that this is not important. There is a limited number of files in any given dataset, users should be able to handle that.

**Comment by hannaboe** [comment]
I agree with Jane that this is not an issue. When uploading readme and aux files first, they are automatically shown on top.
