### ISSUE TITLE
Temporal Extent not mandatory, but required by State-Variable

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#113]
It is not mandatory for a dataset to have temporal extent, but it is for State-Variables (it is computed automatically by looking at the related datasets).

@janeuhd Should it be mandatory to specify the temporal extent for datasets?

**Comment by janeuhd** [comment]
@frafra yes I think it should, although temporal extent could sometimes be just 1 year (if a survey only has been done once).

**Comment by frafra** [comment]
Fixed.
