### ISSUE TITLE
Improve the "Associated data" element in State Variables metadata profile - Add external ones

### ISSUE THREAD

**Issue by mdsnor** [COATnor/COAT_portal_issues#115]
We need to improve the way a user can add "Associated Data" to the State Variable metadata. Currently it allows to pick from a list of available datasets in the Data Portal. Since we decided not to add catalog records of external datasets, it is very important to know which external datasets were used to obtain the given State Variable, for example the datasets obtained from MET.no
The user should have a way to add also links to an external dataset's catalog landing page.

**Comment by frafra** [comment]
Temporal extent for the state variables is computed automatically from the linked datasets, but if we include external resources (which could have a different temporal extent), the temporal extent of the state variables could be wrong. I would suggest to keep the temporal extent as a manual field for state variables too, as it happens for the datasets. What do you think about that @janeuhd?

**Comment by frafra** [comment]
Relevant: // https://stackoverflow.com/questions/14577014/select2-dropdown-but-allow-new-values-by-user/30021059

**Comment by frafra** [comment]
A reference to an internal dataset is different to a reference to an external one (the first is a dataset name, the latter is a link).
I guess we should treat all of them as link in the metadata field, to avoid inconsistencies, but we cannot easily have autocompletion while having custom links. Should we have two different fields or disable autocompletion? We can spend some time investigating a third solution, but is it worth the effort?

**Comment by hannaboe** [comment]
I think either different fields for internal or external datasets or one field without autocompletion would work. What do you think @janeuhd?

**Comment by frafra** [comment]
I found how to get both autocompletion and custom links in the same field. I would suggest that autocompletion would always suggest the full link of the internal dataset, for consistency. Is that OK?

**Comment by hannaboe** [comment]
Sounds good to me.

**Comment by frafra** [comment]
This has been implemented in coatdemo.
