### ISSUE TITLE
Feide logins

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#12]
Users should be able to login using a feide account

**Comment by frafra** [comment]
Code is ready to be tested.

**Comment by frafra** [comment]
Working as expected with a minor workaround of `ckanext-oauth2`; we are discussing with the other developers to find a common solution in mainline.

Copying email and full name from Feide Dataporten. We could also include profile pictures, but NINA is not exposing them on Feide yet.
