### ISSUE TITLE
Protocols filters links are wrong - point to datasets

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#121]
The protocols filters are counted correctly based on protocol records. However, when clicking on the filters, it shows datasets instead.

**Comment by mdlux** [comment]
Probably better to check if same error for State Variables too...

**Comment by frafra** [comment]
It seems a CKAN issue: https://github.com/ckan/ckan/issues/6168

**Comment by frafra** [comment]
We can override `secondary_content` in `templates/package/search.html` and pass a custom `alternative_url` based on the dataset type.

**Comment by frafra** [comment]
`alternative_url=dataset_type` seems to work.

**Comment by frafra** [comment]
Fix committed.

**Comment by frafra** [comment]
@eevasoininen fix deployed.
