### ISSUE TITLE
Bulk upload is slow / 504 Gateway Time-out

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#122]
As each time a file gets update a request to the datacite server is sent, bulk uploads can get slower and slower.

Bug reported by @hannaboe.

**Comment by hannaboe** [comment]
I still get the 'internal error'.

**Comment by frafra** [comment]
I disabled the bulk upload for the moment. I think we could rely on the API instead, to start with the uploads soon.
We have REST API and a Python tool to handle individual uploads, but with a simple `for` loop it should be easy to upload multiple files.

The API are well documented here: https://docs.ckan.org/en/2.8/api/
ckanapi is the Python tool I tested: https://github.com/ckan/ckanapi

How you would prefer to upload the data? Should we provide to you support in writing R functions to upload the data so you can publish such code on https://github.com/COATnor/data_management_scripts or are you fine with using the ckanapi Python script?

**Comment by hannaboe** [comment]
I think an Rscript would definitely be useful, also for others.
I just started to look into the ckanr-package and I think I should manage to write a script for uploading data. Is it okay if I create a fake-dataset on the demo portal for testting? Or is there something I shouldn't do?
If that doesn't work, I could also try the python script. Do you have a script for single uploads that I could test?

**Comment by frafra** [comment]
Feel free to create whatever you want on the demo portal. It is made for that purpose :-)
I think we will rely on the Python tool ckanapi for moving datasets, users and modules between servers, as it is easier, but for uploads ckanr-package seems fine.

**Comment by hannaboe** [comment]
I manually created a new dataset (V_test_dataset) on the demo portal and tried to add a file using `resource_create()` form ckanr. But I get the error: 
Error: 400
Bad Request "Bad request - JSON Error: Invalid request. Please use POST method for your request"

I did the following, do you have any idea what I'm doing wrong? I tried to specify different arguments, but I always get the same error.

`ckanr_setup(url ="https://coatdemo.coat.no/", key = "xxxx")    # setup

resource_create(package_id ="9692a5cb-ab1e-4bb1-b308-9c35402ced79",  # id of the test-dataset I created
                name = "test", 
                description = "test2005", 
                upload = "~/COAT/ckantest.txt")  # path to the file I want to add to the dataset
`

**Comment by frafra** [comment]
It seems to me that the message is misleading

```
  res <- ckan_POST(url, 'resource_create', body = body, key = key,
    opts = list(...))
```
-- https://github.com/ropensci/ckanr/blob/38fd507a669b918e49c8c44619c1a9998b719c70/R/resource_create.R#L72-L73

This is clearly a POST request. What about invalid data? Have you tried to specify a full/absolute path? Is there a resource with the same name already there?

**Comment by hannaboe** [comment]
The error occurs already in the first line of the function ('id <- as.ckan_package(package_id, url = url, key = key'). If I modify the function a lbit so that I can skip this line, the upload works fine.

This means I can do bulkuploads for now, but it is probably not a good solution. Do maybe have an idea why `as.ckan_package()` gives an error?

**Comment by hannaboe** [comment]
I figured out what the problem is and it will be fixed soon:
https://github.com/ropensci/ckanr/issues/109

Anyway, if there are lot of files uploaded already, the upload gets slow and runs into a '504 Gateway Time-out' eventually.

**Comment by frafra** [comment]
I think that performance can be improved overall. Removing the download counter actually avoided many unintentional updates being sent to the DOI server.
Closing for now, but we can and should further improve performances.
