### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#125]
I tried to setup ckanr using the API key I found on the dataportal. But I only see public datasets and can not create new packages or resources. Downloading public files (using`ckan_fetch`) worked fine.
So I was wondering if I used the wrong API key? Do I find it somewhere else than on the data portal?

**Comment by hannaboe** [comment]
I have the same problem with ckanapi. If I run`C:\Users\hbo042>ckanapi action package_list -r https://coatdemo.coat.no -a "xxx"`, I only see public dataset.

**Comment by mdlux** [comment]
Hi Hanna,

there is an option to deal with private datasets too. You have to add in your request:
include_private:True

**Comment by mdlux** [comment]
See page 47 of:
https://cran.r-project.org/web/packages/ckanr/ckanr.pdf

**Comment by mdlux** [comment]
This is an example taken from https://github.com/ckan/ckanapi

$ ckanapi search datasets include_private=true -O datasets.jsonl.gz -z \
          -c /etc/ckan/production.ini

**Comment by hannaboe** [comment]
Thank you, this worked for `package_search()`. I used `package_list()`, and then I only see prublic datasets

**Comment by mdlux** [comment]
I think it's not implemented for package_list
