### ISSUE TITLE
New geographic locations

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#126]
I added some locations to the locality-file (https://uitno.app.box.com/file/526455456143). Could you add them to the dropdown menue for geographic locations? Thank you!

**Comment by frafra** [comment]
Sure! Does that fix #123?

**Comment by frafra** [comment]
It does not seems so. I would wait for #123 to be fixed before doing an update.

**Comment by hannaboe** [comment]
Could you do the update? #123  ist fixed.

**Comment by frafra** [comment]
I am doing it right now ;)

**Comment by frafra** [comment]
Fixed and deployed.
