### ISSUE TITLE
Data management plan download shows "resource under embargo"

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#132]
I tried downloading the data management plan. The file I downloaded was called "resource under embargo". When opened it with Adobe acrobat it proved to be the DMP. Could the name be corrected? It should not be behind embargo (and anyway one should not be able to download a file under embargo;)

**Comment by eevasoininen** [comment]
@mdlux @frafra can you take a look at this? Today I was entirely unable to download the data management plan, only got "resource under embargo" info. We need this to be downloadable by the end of the month to have it available when we send NFR report.

**Comment by mdlux** [comment]
@eevasoininen It looks ok now, can you confirm?

**Comment by eevasoininen** [comment]
Hei, It does not look OK to me, no change from before. I manage to open it, but I do get pop-up "you have chosen to open resource-under-embargo".... maybe call me and we can go through where exactky happens what in my end, its a bit difficult to explain?

**Comment by eevasoininen** [comment]
@mdlux see my answer in previous post,

**Comment by hannaboe** [comment]
This seems to be an issue for all datasets on data.coat.no. 

All urls to data files and protocols include 'resource under embargo' even if they are not under embarg. For example: https://data.coat.no/dataset/b3566daf-3398-497d-a2f0-ea540639ea08/resource/384fe537-e0bd-4e57-8a0d-420b7a745196/download/resource-under-embargo
This means that the files can not be open vie the download button.  Downloading the whole dataset as a zip-file or downloading files via R works.

**Comment by hannaboe** [comment]
And it is only an issue if the datasets were moved from coatdemo. There is no problem with the dataset that has been uploaded directly to data.coat.no.

**Comment by eevasoininen** [comment]
This is actually quite problematic in the open data portal, and very discouraging for anyone downloading data.

**Comment by frafra** [comment]
Datasets have been synchronized from coatdemo. Resources can be downloaded again. Some of them have a "resource-under-embargo" name, which I am working to fix, but they are downloadable.

Performances were terrible due to the combination of the metadata update triggered by the download, which itself triggered a DOI update. Download counting is suspended and has to be implemented differently.

**Comment by frafra** [comment]
Remaining datasets to be fixed:

- [ ] coat-data-management-plan_v1
- [ ] protocol-camera-trapping-of-small-mammals-pilot-study_v1
- [ ] protocol_plant_measurements_heath_and_meadow_varanger_v1
- [ ] v_air_temperature_snowbed_v1
- [ ] v_rodents_cameratraps_pilot_v1

These are not part of the coatdemo.coat.no synchronization, so fixing these datasets require a different approach.

Still not sure about what caused the issue.
