### ISSUE TITLE
Error 413: Request Entity Too Large

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#134]
I wanted to upload a large file (42 269 KB) and got the error 'Request Entity Too Large'.
I was wondering if that's the same issue as with uploading very many files (#122) or if the file size is too big and we have to divide the data file?

**Comment by frafra** [comment]
No, it is a different issue.
We could set it to a higher limit, but it is not a good idea to upload large files. Which file is that?

**Comment by hannaboe** [comment]
It's a file that contains plant species data. And the file is quite long since we have a lot of species and a lot of plots.

**Comment by frafra** [comment]
Plots? Is it a PDF file?

**Comment by hannaboe** [comment]
Sorry, I meant the plots where we do measurements (similar to sites), not figures. It's a txt file, as all the other data files.

**Comment by hannaboe** [comment]
Could you set the files ize to a higher limit? Or should we split the file?
The file size is 42500 KB.

**Comment by frafra** [comment]
This seems an issue which is related to NINA servers, not to our catalog, which seems to be able to support even 500 MB at once with a fast connection.

@mdlux you worked with Datahjelp on that, right?

**Comment by mdlux** [comment]
Yes, but apparently what they did was not enough. More troubleshooting needed

**Comment by mdlux** [comment]
It is fixed now, extending the limit on the reverse proxy (nginx) was enough.
