### ISSUE TITLE
Link external dataset with state variable

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#137]
When adding a state variable ther should be the possiblity to link an external dataset (for example a rasterdataset from GeoNode). At the moment, it is only possible to link datasets from the COAT data portal.

**Comment by janeuhd** [comment]
@frafra @mdlux 
This is as we discussed at the last meeting. There are several cases where ecological state variables might be based on data which are not in the portal:
1) the state variable is based on remote sensing data from an international repository 
2) the state variable is based on raster data which are/will be in NINAs GeoNode
3) the state variable is based on field data collected by someone else and in another repository such as GBIF
4) the state variable is based on camera traps or sound stations, where the images/sound files are/will be on Sigma-2

**Comment by mdlux** [comment]
relates to #115
