### ISSUE TITLE
Adding several resources to an existing dataset 

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#141]
Could we have a possibility to add several resources to an existing dataset in one go? Currently, when creating a new version and wanting to add several files to it, one needs to click through the whole "manage, resources, add new resource"- path in between every added resource. In contrast, when one creates a new dataset one has an option to save and add more files while being in the same resource-adding window.

**Comment by hannaboe** [comment]
A work around is to use the bulkupload-script. It is on box (COAT\Data Management\data_management_scripts)) and will be also available on https://github.com/COATnor/data_management_scripts  when my PR is accepted.

**Comment by mdlux** [comment]
PR accepted
