### ISSUE TITLE
Move up metadata

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#143]
It would be great if the metadata-box could be moved up or list with data files could be shortend. At the moment you have to scroll through all files to get to the metadata box (and there are datasets with hundreds of files).

**Comment by eevasoininen** [comment]
This is quite important! See example with the temperature datasets https://data.coat.no/dataset/v_air_temperature_snowbed_v1 that become hilariously long before one finds the metadata :)

**Comment by frafra** [comment]
I doubt that user gain benefits from having data split in so many files that should be downloaded individually, but since we went down that road, I moved the resources list under the metadata table in coatdemo :)
