### ISSUE TITLE
Can not select all protocols

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#144]
When creating a new dataset, it is not possible to select the 'Associated study protocol' from all protocols (on coatdemo). It seems the list shows only the protocols which have been uploaded recently.

**Comment by hannaboe** [comment]
The same goes for datasets when creating a state variable. It is not possible to select the associated dataset from all datasets.

**Comment by frafra** [comment]
You are right. I found the issue and developed a patch. The fix will be deployed soon.

**Comment by frafra** [comment]
Fix deployed.
