### ISSUE TITLE
Publish datasets on coatdemo or data.coat.no?

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#148]
Should datasets that have been uploaded to coatdemo earlier be published on coatdemo and then moved to data.coat.no? Or should they be moved first and only be published on data.coat.no?

**Comment by mdlux** [comment]
We are moving datasets from coatdemo to data.coat.no, and every new operation will be on the offical dataportal. Coatdemo will be just a test environment for new functionalities.
