### ISSUE TITLE
 Can not create new state variable

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#150]
I tried to create a state variable on coat demo, but got an 'internal server error' when clicking on 'Add Data'.

**Comment by frafra** [comment]
Which dataset was that?

**Comment by frafra** [comment]
Hi,
which dataset was it? Was it test_dataset_v1? Which file was that? I am not able to reproduce at the moment: could you please provide more details?

**Comment by hannaboe** [comment]
It was not a dataset but a state variable. I don't think that a state variable was created at all, but can unfortunately not check that at the moment since I still can't log in.

**Comment by hannaboe** [comment]
The same happens when creating a new dataset.

**Comment by frafra** [comment]
Oh, that should be something else, sorry.

**Comment by frafra** [comment]
It has been fixed locally, but it required two changes to two external dependencies. I am working with the developers upstream for that.
Major improvements have been made to the filtering for the linked datasets also.

I am going to deploy the new version in testing soon, while I tackle the remaining major issues.

**Comment by frafra** [comment]
New version deployed. State variable creation works.
