### ISSUE TITLE
How do I add a keyword or filter in the database?

### ISSUE THREAD

**Issue by ingridgarfeltpaulsen** [COATnor/COAT_portal_issues#155]
Hei,

Under 'Create data' in data.coat.no I would like to add keywords or scientific names of species that are not already included in the list. How do I make user defined keywords or scientific names? This issue will also come up for geographic locations for 2021 vegetation data in Svalbard since we have added new sites on Stuphallet, Brøggerhalvøya.

Ingrid

**Comment by frafra** [comment]
Hei,
users cannot write freely in these fields, as values are pre-defined.
To change such presets, you need to tell us what to add, and we will take care of it.

**Comment by janeuhd** [comment]
@ingridgarfeltpaulsen please note that any additions to our taxonomies (such as adding new species or new localities) needs to be made in the files on BOX Box\COAT\Data Management\Taxonomy. Once they have been updated in the taxonomy files you can ask frafra to add the new words to the dropdown lists in the data portal.

**Comment by ingridgarfeltpaulsen** [comment]
Okei, will do !
