### ISSUE TITLE
Datasets with embargo can not be downloaded from data.coat.no after automatic transfer

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#156]
Datasets with an embargo that have been uploaded to coatdemo.coat.no and were moved automatically to data.coat.no can not be downloaded by logged in useres . The url of the datafiles is: #resource-under-embargo.

It seems to be only an issue when the datasets have been moved automatically. If a new file is uploaded directly to data.coat.no (to a new version of a moved dataset), this file has the correct url and can be downloaded, all the other files have url that contains 'resource-under-embargo and can't be downloaded.

This is probably also the reason for the downloading error (#151).

**Comment by frafra** [comment]
Hei Hanna,
I have been working on that for a while. Fixing it requires a major upgrade of the whole software (from CKAN 2.8.4 to CKAN 2.9.4) and I am halfway through that. I would like to have it fixed in a couple of days.

**Comment by frafra** [comment]
Hi again,
such upgrade is requiring more time than expected, but it is moving forward. I will keep you posted.

**Comment by hannaboe** [comment]
Hei, I was wondering if we can add new data from 2021 to the datasets or if we should wait until this is fixed?

**Comment by frafra** [comment]
Hei Hanna,
it would be better to wait, if that is reasonable for you.

**Comment by hannaboe** [comment]
That's okay.

**Comment by frafra** [comment]
Our portal is fine, but the software to synchronize the datasets cannot read private dataset, hence the issues with strange symbols and such.
We have a working mechanism in place, thanks to a solution that we develop.
Such improvement should also be integrated in the software we rely on, but the maintainers required a more comprehensive fix: https://github.com/ckan/ckanapi/pull/195

I am working on a test suite to make the whole catalog more robust and double check if we have issues with private/public/embargo datasets, and to avoid further regressions.

**Comment by frafra** [comment]
A simple workaround at the moment is to re-upload resources.

**Comment by frafra** [comment]
Closing this issue, as the synchronization mechanism is not going to be used again and we will proceed manually.
