### ISSUE TITLE
Can not select multiple values for one meta data field

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#157]
I did some testing on coatdemo and it looks like we can't select multiple values for a metadata field anymore.

This is the case for the following meta data fields:
- Tags
- Associated Parties
- Geographic Location
- Scientific Name

**Comment by frafra** [comment]
I am able to do that by pressing the `SHIFT` keyboard button, but the autocompletion mechanism does not work, which is a regression brought with the big upgrade (CKAN 2.8 to CKAN 2.9 with Python 3).
I am going to take care of that. Thanks for your feedbacks :)

**Comment by frafra** [comment]
Autocompletion has been reworked. Tags still need to be selected holding SHIFT.
