### ISSUE TITLE
Tags/Keywords are ignored when creating new dataset

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#158]
When creating a new data set, the selected tags are associated with the dataset.

**Comment by frafra** [comment]
I can confirm there is a problem with that, a regression indeed.

**Comment by frafra** [comment]
I am now able to associate tags to datasets.
The latest version on coatdemo shows the real value of the tag (like `air_temperature` instead of its representation, `Air temperature`), but it can be improved later if needed.
