### ISSUE TITLE
Filtering gives an error

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#159]
The filtering functions for filtering datasets after location, module... on the left site of the page does not work. It gives a '404 Not Found' error.

**Comment by frafra** [comment]
Issue belongs to CKAN: https://github.com/ckan/ckan/issues/6806
Issue fixed via workaround. Fixed portal is going to be deployed before Easter.

**Comment by hannaboe** [comment]
Can you let me know when the fixed portal is deployed?

**Comment by frafra** [comment]
It has been deployed on coatdemo already. I am going through the other issues and then deploy to the official website.
