### ISSUE TITLE
Visualization errors in resource view for some data types

### ISSUE THREAD

**Issue by mdsnor** [COATnor/COAT_portal_issues#16]
.csv files are not properly visualized, while .txt are. Even a .csv file if labeled .txt can be visualized as a text.
Seems an error in the Data Explorer view (associated to csv files). The TEXT and Image views work properly.

**Comment by frafra** [comment]
CKAN developer say that the preview function will be deprecated entirely in the future. Should we keep it active and try to fix the bugs or just remove it?

**Comment by mdlux** [comment]
I think it is a nice functionality, and we should try to fix it in near future.

**Comment by frafra** [comment]
We should try to enable the datastore plugin.

**Comment by mdlux** [comment]
Enabling the datastore solves the issue. However, there are some conflicts with the datasets-version code, to be further investigated, before adding the datastore.

**Comment by frafra** [comment]
It would still be interesting to figure out why it is not working in the first place. It could be a bug, a common issue maybe.

**Comment by frafra** [comment]
The portal does not seem to have CSV.
