### ISSUE TITLE
Can data files be uploaded in bulk form the web interface?

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#17]
Implementing batch upload of several files within the same dataset (ex. one file per year in 10 years)

**Comment by frafra** [comment]
Discussion started on: https://github.com/ckan/ckan/issues/5023

**Comment by frafra** [comment]
We found a workaround, by using https://uppy.io/ and https://tus.io/. This would also allow simple post-processing and metadata extraction from files potentially.

**Comment by frafra** [comment]
I found https://github.com/OriHoch/ckanext-file_uploader_ui which provides a better integration with ckan. Note that, compared to tus.io, the file size is limited by the web server, as it already happens when uploading resources individually.

**Comment by frafra** [comment]
Deployed in demo. Minor graphical glitch reported: https://github.com/OriHoch/ckanext-file_uploader_ui/issues/2
