### ISSUE TITLE
Errors in metadata validation

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#18]
Some errors for metadata fields set to "required". As a temporary workaround, metadata validation is temporary disabled.  For the moment even if some fields are marked as required, no real validation is performed, and missing values are accepted. Needs to be solved asap.

**Comment by frafra** [comment]
Metadata validation should be ignored when creating the pseudo-dataset which keeps track of the versioned datasets.

**Comment by frafra** [comment]
In addition to `"required": True`, a validator should be added to avoid errors.
The validation on required fields now works as expected, but it has been removed from the `tags_string` list.
