### ISSUE TITLE
Metadata info, name check, and multiple geographical locations

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#2]
A few issues came up on the meeting on Friday:
* Metadata: Some metadata fields have an (i) with a short description below the field. We would like to have this on all fields which are not completely self-explanatory.
* Avoiding replicated file names: is there at present a check of replicate filenames/datasetnames when uploading? Is this possible? We should avoid replicated filenames, also between datasets.
* Metadata: At present it is only possible to choose one _Geographical location_. Could it be made possible to choose multiple locations? Example: we might have a dataset which is sampled at several locations (say Komag and Vestre Jakobselv). We would want this to appear in both a geographical and topical search on both these names. 
* Portal menu: Can 'Groups' be renamed to 'Modules' (more specific to the way we plan to use groups, and immediately recognizable for people familiar with the COAT monitoring modules)?

**Comment by frafra** [comment]
I will reply to the questions not related to the metadata, which I leave to @mdlux.

> * Avoiding replicated file names: is there at present a check of replicate filenames/datasetnames when uploading? Is this possible? We should avoid replicated filenames, also between datasets.

No problem with that. I can take care of it.

> * Portal menu: Can 'Groups' be renamed to 'Modules' (more specific to the way we plan to use groups, and immediately recognizable for people familiar with the COAT monitoring modules)?

Sure, that is not a problem at all.

**Comment by mdlux** [comment]
Anyway, for more granular management, I will create an issue for each specific question

**Comment by mdlux** [comment]
Splitted in 4 different issues, closing
