### ISSUE TITLE
Support for multiple species from the taxonomy list

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#22]
Taxonomy list should be generated from the files available on Box.

**Comment by frafra** [comment]
Current way to label entries: use "Family - Species - Genus - Latin name (Norwegian name)" and skip missing parts (missing columns or "NA" values).

@janeuhd Does it make sense to you? Here is what it looks like on my PC:

![Screenshot_2019-11-06 Datasets - COAT Data Portal(1)](https://user-images.githubusercontent.com/4068/68319297-66667b80-00be-11ea-9a79-dc4014b33fa3.png)

Auto-completion fully working on that field.

**Comment by janeuhd** [comment]
Yes that looks good!

**Comment by mdlux** [comment]
I think it would be nice to update family names where missing in the lists we are using (ie: birds)

**Comment by frafra** [comment]
Thanks Jane. It is now available on the demo instance.

The new mechanism for auto-completion has been applied to the tags and locations fields too. That should make easier to find and select the items.
