### ISSUE TITLE
How to upload datasets?

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#24]
I'm trying to start testing the data portal. Could easily find my way around datasets and modules, but not where should I go to upload a new dataset. Could this be an easily available visible button/choice somewhere? Or is it just so that I do not happen to have the editorial rights yet? Takk :) Eeva

**Comment by mdlux** [comment]
Hi Eeva, you are right, the button will be visible only to those who are "editors" of a module. As soon as we have a list of editors for each module, we will upgrade your statuses.
