### ISSUE TITLE
Github script repositories

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#28]
@frafra 
This issues concerns the github repository, not the portal.
Can we rename and add, so that we have 3 repositories for scripts?

Data upload/download scripts (batch processing etc)
Data analysis scripts (the 'official ' scripts that we share with the world)
Data maintenance scripts (our internal scripts for quality checking, preprocessing etc)

**Comment by frafra** [comment]
Repositories has been renamed, descriptions has been updated, and a third scripts repository for data analysis has been created.

GitHub does not allow to have private repository in groups with more than 3 members for free. In case we want to keep the data maintenance and data management scripts private, I would suggest to switch to our internal NINA GitLab server (opensource GitHub-like solution integrated with NINA accounts).

**Comment by janeuhd** [comment]
Thanks. It is not really important to keep them private. But for our own sake it is important to keep them in separate repositories.
Closing
