### ISSUE TITLE
Metadata interface - end date - how is it changing?

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#30]
When a dataset is created, one needs to give an end-date. Should this be an end date for time-series that really have been stopped, or the last date that is in the existing data? What happens when new data are added? Does one need to modify the metadata? Info about this would be good to have next  to the end-date field.

**Comment by mdlux** [comment]
Hi, this is policy decision, which should be made by the COAT leadership.  If it is interpreted as the current end date of the existing data, the dataset metadata need to be updated at any new resource addition. To update such info an editor or admin need to click on the "Manage" button, and edit metadata. The dataset need to be set to private mode before such a change, and ideally a new dataset version should be created. Then publish the newest version. @janeuhd ?

**Comment by janeuhd** [comment]
The end date is the current end date of the data set, also for data sets which will continue next year. When another year of data is added, a new version is made, so it is not a problem that we also have to update the metadata.

**Comment by eevasoininen** [comment]
OK, then this should be noted in the info next to the end date field. Probably we should also make a little "what to do when you update a dataset?"

**Comment by mdlux** [comment]
added help text
