### ISSUE TITLE
Metadata interface - tags/keywords

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#31]
The field has a "start typing" function that should give suggestions from a list as one starts to write? It is great as we can avoid spelling same thing in different ways.

It did not suggest any other words than those that I had already written from my computer into that field previously.

**Comment by frafra** [comment]
Hei eeva,
that should have been just been fixed few minutes ago :-) You now have completion for tags, locations and scientific names.

Feel free to close this issue if it works for you as you like.

**Comment by eevasoininen** [comment]
It works now :)
