### ISSUE TITLE
Metadata interface - license 

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#32]
Here we should have some COAT-specific info explaining what these are. Eg "all COAT datasets should have licence xyz (meaning that its allowed to use them for anything). Exeption are datasets with characteristics like abc (example), that should have licence XYZ". Otherwise it is unlikely very clear for most of us what to choose.

**Comment by frafra** [comment]
CC-BY 4.0 should be the default one, while NLOD should be used for some specific datasets, but I do not know which at the moment.

**Comment by mdlux** [comment]
I think it's a policy decision. COAT researchers (or leaders) could decide that all COAT datasets defaults to CC-BY 4.0, unless there are strong reasons to specify a different license (NLOD, in this case). If such a decision is taken, it would even simplify the metadata writing, because we could remove the license choice (which would be added automatically by the system to the metadata, without displaying it in the form).

**Comment by eevasoininen** [comment]
Yes, I agree its a policy decision. We need to take it sort it out and come back to you. 

But - if there is a choice - we need to give description and/or example because not many of us understand what the license names mean.

**Comment by janeuhd** [comment]
The policy in COAT is CC-BY 4.0 unless compelling reasons not to. I think we can keep the choice in metadata, but add in the info tag below the field, something like "CC-BY 4.0 is the default choice in COAT", and very briefly what sets NLOD apart from CC_BY (when could it be chosen)?

**Comment by eevasoininen** [comment]
Agree with @janeuhd, this info should be added.

**Comment by frafra** [comment]
Should we stick to CC-BY 4.0 only? NLOD is similar to CC-BY-SA, but I do not believe the Share Alike clause is relevant if you do not want to have back changes that people and other researchers are doing to COAT data.

In my opinion, source codes can use more copyleft licenses (with share-alike clauses, to keep the modification available to everybody and having them merged back into the original project if relevant), while with open data it usually better to stick to more liberal licenses like CC-BY (or even CC-0 in some cases).

**Comment by frafra** [comment]
CC-BY 4.0 has been set as the only possible option.
