### ISSUE TITLE
Metadata interface - affiliations

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#33]
Here we could have a "start typing" function so that we could pick affiliations from a list (with possibility to add if one needs to define something else). Otherwise we risk several variants of the same institute name.

**Comment by frafra** [comment]
Good; we could have a autocomplete field which also accept extra values if needed.

Do we have such a list of affiliations?

**Comment by eevasoininen** [comment]
I just sent such a list under the issue that I wrote about organizations. Sorry for making untidy threads!

**Comment by mdlux** [comment]
The list is in #40

**Comment by frafra** [comment]
Closed as publicated of #40.
