### ISSUE TITLE
Metadata solutin - taxonomy

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#35]
Should we have a way to make the list of taxa related to the COAT taxonomy list somehow? So that we do not get all sorts of variants here? Some advice what to write or a "start typing" field?

**Comment by janeuhd** [comment]
The list of taxa should already be identical to the names in the COAT taxonomy lists? Did you find any species missing?

**Comment by eevasoininen** [comment]
It works now. This is a comment I wrote down last afternoon when testing.

**Comment by mdlux** [comment]
Seems solved. Closing

**Comment by eevasoininen** [comment]
Sorry, another issue on taxonomy. The bird list seems not to be there?

**Comment by frafra** [comment]
It was missing indeed. Fixed. See #42.
