### ISSUE TITLE
Metadata solution - going back to edit

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#38]
I was not able to go back to edit the fields of the first page:

I tried first to make a public dataset, and got a message that this was not possible. I tried then to go back to change the field from public to private. This was not possible and I had to re-enter everything.

**Comment by mdlux** [comment]
This is a consequence of other issues. When fixed, it shouldn't happen again. See #26 and #37

**Comment by eevasoininen** [comment]
It seems to work now; I was able to go back from "add data" to "create dataset" without loosing any info.
