### ISSUE TITLE
Metadata solution - some guidelines to "useful information"

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#39]
We should write some guidelines as to what we mean with "useful information". I suggest something like: "For example which files/content that dataset consists of, how often these are added, or how often the data is sampled"

**Comment by mdlux** [comment]
Yes, this is important. In general we need some good documentation about how the Data Portal interface works. This should ideally integrated with the Data formatting guidelines to build a complete documentation of the COAT Data Management procedures. Documentation is planned and will come asap.

**Comment by eevasoininen** [comment]
This should stay open; there is no info yet as what the Description field should contain. Will you draft something that is in line with general requirements for metdata (?) and we can then comment?

**Comment by mdlux** [comment]
Something like:
"Short description of the dataset, including relevant information about the content, data type, sampling method and frequency or source. Include any detail helping to understand the dataset's characteristics. Include a bulleted list of data file types included as resources to this dataset (ie: yearly txt with transect data, a coordinates CSV file, auxiliary file with details, etc.)"

**Comment by janeuhd** [comment]
Yes. I think that should be sufficient explanation.

**Comment by mdlux** [comment]
Done
