### ISSUE TITLE
Metadata: choose multiple locations

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#4]
At present it is only possible to choose one Geographical location. Could it be made possible to choose multiple locations? Example: we might have a dataset which is sampled at several locations (say Komag and Vestre Jakobselv). We would want this to appear in both a geographical and topical search on both these names.

extracted from #2

**Comment by mdlux** [comment]
This complicates the Location management. In current model, the chosen location relates to some coordinates, used also for the bounding boxes. How to deal with that? 

Wouldn't be a solution to separate such a dataset in 2 different ones, maybe with similar names (maybe just adding the location to name?), same metainformation and just a different location (and files)? It would even make it simpler to download only those data files related to a specific location.

**Comment by janeuhd** [comment]
I thought it would. The reason for the request is that we have certain types of datasets collected at multiple locations which should not be analysed (or distibuted) individually (for instance two constrasts in same design, located in different valleys). It would be more correct to keep them as one dataset. If we cannot tag then with multiple locations, we would need to choose the top level (Varanger) as geographical location. I guess that means that they will show up in any spatial search anywhere on Varanger? In a topic search on their actual location name (say Komagdalen) they would not show up? But perhaps this can be managed by adding the more detailed locations to keywords?

**Comment by mdlux** [comment]
We will try to implement a multi-location approach. Keep you updated

**Comment by mdlux** [comment]
Done
