### ISSUE TITLE
Metadata solution - organizations

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#40]
We have now two ways of defining organizations; as modules (where we collect data) or as institutions (as me and Jane had written in the metadata). This becomes confusing ;) 

Should we change terminology to "COAT modules" and "Institutions"? Or is there some other way to clarify this?

**Comment by eevasoininen** [comment]
Just discussed with Jane. Apparently this is already almost fixed. What we should have in the metadata entry when adding "Organization Name" and "Associated Parties", should be a drop-down menu with following:

UiT - The Arctic University of Norway 
NPI - Norwegian Polar Institute 
NINA - Norwegian Institute for Nature Research 
MET - Norwegian Meteorological institute 
UNIS - University Centre on Svalbard 
AU – University of Aarhus 

it should also have the possibility to add more names, and ideally so that once a new name is typed its added to the drop-down list so that when someone else wants to use it one can pick the same spelling.

**Comment by mdlux** [comment]
I think that switching from "Organization name" to "Institution name" as field name could be wise. What do you think @janeuhd ?

**Comment by janeuhd** [comment]
If it is not causing trouble in relation to metadata standards (?) then that would be fine. We should substitute "Organization" with "Modules" in as many places as possible, to avoid confusion. This includes the left hand panel under Modules (where the module is summarized according to organizations, tags, groups etc)

**Comment by mdlux** [comment]
Question: Is it necessary to keep 2 different fields? Instead of having both Institution name and affiliations, could it be possible to keep only a single field with multiple possible values? The main organization could be deducted by the point of contact... 
More in general, what is the purpose of this metadata field(s)? to inform about the institutions involved in that specific dataset collection?

**Comment by eevasoininen** [comment]
Answer to Matteo: I think its fine to keep two fields: one that informs where the contact person is affiliated, and one which tells which other institutions/organizations are involved in the dataset collection.

**Comment by mdlux** [comment]
ok, thanks

**Comment by mdlux** [comment]
Done. However, new institutions in dropdown list need to be added manually by sysadmins.
