### ISSUE TITLE
Birds are missing (was: Metadata solution - taxonomy)

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#42]
Sorry, its not entirely fixed. The bird list seems to be missing from there.

**Comment by frafra** [comment]
You are right, thanks. It was due to different file naming (`Taxonomy/Bird` folder has the taxonomy file with a lowercase `f` in `_final.csv` compared to the others).

**Comment by frafra** [comment]
That should be fixed in the latest deployment of the demo instance I just did few minutes ago.

**Comment by eevasoininen** [comment]
Yes it seems to be fixed.
