### ISSUE TITLE
Error when adding the same file twice by mistake

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#43]
When uploading a new data set, I tried adding one of the files twice by deliberate mistake. I got an error page - all well so far. But the only way I could get out of the error page was the back arrow. And when I did that the page looked like picture below. I could not get back to the data files I have already uploaded, or remove the file that caused the error. When I press 'previous' I was send back to the metadata, and all the files that I had added were gone.
This is a mistake that could very easily happen when adding files one-by-one. The response should be that the doublet file is not added, but not that we are thrown out of adding files all together. Can this be fixed?

![image](https://user-images.githubusercontent.com/35291431/68463221-74c3ad00-020e-11ea-92c0-9568bdf962bc.png)

**Comment by frafra** [comment]
I am working on the validators to improve the error handling. Thanks for the feedback.

**Comment by frafra** [comment]
I did a major overhaul of the error handling this evening. This kind of issues related to error messages should be gone now.
