### ISSUE TITLE
editors and what others can see

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#44]
Hanna and Ragnhild tried to add datasets now, but they have not been added as editors. They were on the test phase editor list, can they be added? 

They could also not see any datasets, It seems that anyone else from COAT is not editor but "only" a member, and tries to take a look, will not see any datasets? It would be practical if people could see what we have set up to get an idea of how the portal looks and works.

**Comment by janeuhd** [comment]
In order to see the data sets they need to be members of the modules. Probably there has been a slight delay in them being added as members. I'll see if I can fix it.

**Comment by janeuhd** [comment]
They have now been added as module members

**Comment by mdlux** [comment]
members can see private datasets in modules.
Editors can create datasets in modules.
anyone else can only see public datasets.
So, if Hanna and Ragnhild need to create datasets, being members is not enough. I will upgrade both to editors.

**Comment by mdlux** [comment]
I see Hanna and Ragnhild are already editors. Closing
