### ISSUE TITLE
Possible to add new keywords?

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#49]
There may be cases when other words than keywords from the existing list would be relevant to add as "tags". Is there a way to add more on that list?

**Comment by mdlux** [comment]
The choice was to use a controlled vocabulary to avoid the default behavior (users adding whatever new keyword). Of course the list can be updated, and currently it is only us (system administrators) who can update the list. Adding a new functionality which allows some users (editors? admins?) would require additional work; is it really necessary? Do you expect adding new keywords often? Is it enough that we add such new keywords on your behalf, whenever needed?

**Comment by eevasoininen** [comment]
I do not expect this to be necessary very often. So I think its fine that you add words if we have some we want to add. So no, not necessary to add a new functionality on this.
