### ISSUE TITLE
Avoid duplicate names (datasets, resources)

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#5]
is there at present a check of replicate filenames/datasetnames when uploading? Is this possible? We should avoid replicated filenames, also between datasets.

Extracted from #2

**Comment by frafra** [comment]
@janeuhd We currently block duplicates within the same dataset. I can implement a mechanism to block duplicates over different datasets (but not on different versions of the same dataset).

**Comment by frafra** [comment]
Fix implemented, two different policies are available:

- Local check: check if there is a resource with the same name _in the very same versioned dataset_
- Global check: local check + check if there is a resource with the same name in other datasets.

COAT catalog will be deployed with the global check tomorrow.
