### ISSUE TITLE
Scientific names are stored with "u" in front of them sometimes

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#53]
Some bad unicode/u-prefix bad handling going on probably.

**Comment by mdlux** [comment]
This happens with location names too

**Comment by frafra** [comment]
The list of choices is stored as a string. Python 2 represents unicode strings with an "u" prefix.
Using `json.dumps` allow to dump list to string and avoid this issue.

**Comment by frafra** [comment]
Fixed with a custom validator applied on scientific names and locations.
All the dataset has been updated.
