### ISSUE TITLE
Dataset counter not updated in Dashboard/My Modules

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#54]
The dataset counter in Dashboard/My Modules is not updated when datasets are added. Does it only count published datasets (as the overall counter on the front)? It would make sense if that counted also unpublished data sets.

![image](https://user-images.githubusercontent.com/35291431/68652955-e9f2f300-052a-11ea-91a4-7688091d54dc.png)

**Comment by mdlux** [comment]
I think it works well. when you are logged in, you will see the datasets you are allowed to see. Non-logged users will only see published datasets. As an admin you should see them all, can you @janeuhd ? I think it is how it should be.

**Comment by janeuhd** [comment]
No, that is the point. I'm logged in, and  my dashboard should hence show how many datasets are added to each module. But all counter show '0'. 
If I go to Datasets, then the counters are correct, but not in dashboard.

**Comment by mdlux** [comment]
Ok, I see now. It's a bug.

**Comment by mdlux** [comment]
https://github.com/ckan/ckan/issues/5156

**Comment by frafra** [comment]
Need to rebase our software on top of patched version of CKAN.

**Comment by frafra** [comment]
We are now running CKAN 2.8.4 (plus NINA/COAT patches). The bug has been fixed.
