### ISSUE TITLE
Add scientific names to search facets

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#55]
We need to add some more data search filtering criteria in the facets (the search filter column on the left in /dataset page)

**Comment by frafra** [comment]
I would also suggest to use helpers to show the labels instead of the values if possible.

**Comment by frafra** [comment]
Scientific names added. It would be nice to store labels on the database, but it is not working.

If more facets are needed, I would suggest to open a new issue with a full list of what is needed, or create multiple issues if it makes sense.
