### ISSUE TITLE
When "Manage" public datasets, the visibility defaults to private

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#56]
when publishing a dataset, then updating it with the "Manage" button, the visibility defaults to private instead of public. Probably this is how it should be (a published dataset should be permanent, and if we change something, we should also create a new version). However, as it is now, it could be confusing. If someone updates something, could not know or notice that this operation makes the dataset private, and expect it is still public. Should we add some warning, or communication, making it explicit? @frafra ?

**Comment by frafra** [comment]
I suppose that the new visibility field, which tries to mimic the original one, does not restores values properly, so the first option is always selected.

**Comment by frafra** [comment]
The select preset was not enough, because it compares the database value (which is boolean) with the available options (which are converted to string by default). I took some code by the original `organization.html` file and it worked just fine.

Fix deployed.
