### ISSUE TITLE
Rename "Organizations" to "Modules"

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#6]
Can 'Groups' be renamed to 'Modules' (more specific to the way we plan to use groups, and immediately recognizable for people familiar with the COAT monitoring modules)?

Extracted from #2

**Comment by frafra** [comment]
Isn't this issue dependent on #15?

**Comment by mdlux** [comment]
Instead of groups we will use "Organizations", which provide more isolation and useful authorization rules for members. Organizations will be renamed to "Modules" and "groups" disabled. 

This choice will affect both #14 and #15. Module leaders will be editors. 
See:
https://docs.ckan.org/en/2.8/maintaining/authorization.html

**Comment by frafra** [comment]
> Module page:
> All use of ‘organization’ should be changed to ‘modules’ E.g. “What are Organizations?” should be changed to “What are COAT Modules?”,  “Search organization”, should be “Search modules” etc

-- Jane

**Comment by frafra** [comment]
I would propose to just use a translation file to replace all occurrences instead of changing all the templates and views.

**Comment by mdlux** [comment]
Used a translation file instead, it works fine. closing
