### ISSUE TITLE
Automate resource citation metadata

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#62]
Resource citation metadata field should be created automatically by the system, not displayed in form but in dataset visualization only. It should be a string with a standard formatting based on other metadata. For example:
Jepsen J et al., 2019, forest sapling polmak v1: COAT project data, https://coatdemo.frafra.no/dataset/v_forest_saplings_polmak_v1 (https://doi.org/xx.xxxxx/YYYYYYYY).

The DOI should be used instead of URL, if available.
The COAT leadership should decide the exact format for such a citation.

**Comment by mdlux** [comment]
Or:
Please cite as: Jepsen J et al., 2019, forest sapling polmak v1: COAT project data. Available online: https://coatdemo.frafra.no/dataset/v_forest_saplings_polmak_v1 (https://doi.org/xx.xxxxx/YYYYYYYY).

**Comment by janeuhd** [comment]
Great if this can be automated. I've asked @ngyoccoz to comment on this, so that we can agree on a format. Leave open until then.

**Comment by janeuhd** [comment]
I have not received an answer from @ngyoccoz on this. I suggest we implement it as suggested by Matteo. It is in accordance with FORCE11, and should be sufficient.
 
Jepsen J et al., 2019, forest sapling polmak v1: COAT project data. Available online: https://coatdemo.frafra.no/dataset/v_forest_saplings_polmak_v1 (https://doi.org/xx.xxxxx/YYYYYYYY).

**Comment by ngyoccoz** [comment]
Sorry – at a workshop and had to get exams done… Just do as suggested by Matteo.
Nigel

**Comment by frafra** [comment]
Ok! I am working on that right now.

**Comment by frafra** [comment]
Done. The field is now automatically filled when a dataset is created or updated.
