### ISSUE TITLE
R-script for requesting dataset from testportal

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#63]
Is it premature to start testing how we can request a full data set (or files) from the portal using R? I don't know how to do that, can @frafra @mdlux help?

**Comment by mdlux** [comment]
Hi @janeuhd , would it be possible to set some (or just one) of the datasets to public?

**Comment by mdlux** [comment]
Have a look at the ckanr library designed to interact with CKAN API:

https://github.com/ropensci/ckanr

I added some examples in our data management repo:

https://github.com/COATnor/data_management_scripts/blob/master/coat_test.R

**Comment by janeuhd** [comment]
thanks @mdlux 
I'm not too eager to set the data sets uploaded so far to public, but we can upload a dummy dataset if this is needed. Do data sets need to be public in order to be requested? We will need functionality that permits internal users to request also non-public data.

**Comment by janeuhd** [comment]
@mdlux 
I have added a dummy dataset (v_dummy_data) and set it to public. It contains random values but have otherwise same file structure as the real files.

**Comment by janeuhd** [comment]
@mdlux 
I have made an extended version of your script, and can access the public dummy dataset, and also download single files. But I'm struggling with how to download a full package in one go? I'll email the script to you for now, as I don't have write access to the script repositories (see issue #64 ).

**Comment by mdlux** [comment]
@janeuhd having a dummy public dataset helps testing all the cases. Private datasets also can be accessed, but not all operations are supported in API. We are checking the details. Getting public datasets is obviously easier (for a good reason: security). If needed, we can add new functionalities to API.

**Comment by mdlux** [comment]
@janeuhd , you can push the script now

**Comment by janeuhd** [comment]
done!

**Comment by mdlux** [comment]
To download e full package you add "/zip" to the URL of a package. We will test how to do that in R.

**Comment by mdlux** [comment]
@janeuhd some commands to download the zip added to:
https://github.com/COATnor/data_management_scripts/blob/master/request%20data%20from%20COAT%20API.R

**Comment by janeuhd** [comment]
Thanks, but I have an issue with the zipped download. When I try to download the entire public dataset as a zipped file, the zipfile only contains 1 file (the first in the list of resources)?

**Comment by mdlux** [comment]
OS related. On linux it works fine, on windows not. I will check further

**Comment by mdlux** [comment]
Should be fixed. Could you check now, @janeuhd ?

**Comment by janeuhd** [comment]
I still only get the 2013 file in the zipped download.

**Comment by mdlux** [comment]
Did you try:
dnlzip <- download.file(remote_zip, destination, mode="wb")

**Comment by janeuhd** [comment]
No sorry I missed that. It works with mode="wb". Thanks & closing for now.
