### ISSUE TITLE
Access to private and public datasets - discussion of workflow

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#66]
-------
Below copied from email from @mdlux today 

Me and Francesco need to improve the API, so that you can access also private datasets. Upon completion, it will be relatively easy: it is again managed as different version. For example, a possible workflow could be:

-	Jane uploads a dataset which includes only data which can be public (lets say: from year 2000 to year 2017), and calls it “sample_dataset”
-	Such dataset will automatically labelled as “sample_dataset_v1”
-	Jane publishes sample_dataset_v1 
-	Jane creates a new version using the “New version” button, which will be automatically called “sample_dataset_v2”
-	Jane adds 1 year of the data to be kept in embargo, so that “sample_dataset_v2” includes data files from 2000 to 2018.
-	Jane keeps sample_dataset_v2 private, with an embargo date set to 2020
-	Jane creates another version sample_dataset_v3 including year 2019 (again, private), with embargo date 2021
-	Jane uses ckanr to download with R (or python) sample_dataset_v3
-	After 1 year, jane creates a new version, sample_dataset_v4, to include 2000 to 2020
-	Jane will be downloading v4 with R instead of the previous one
-	Sample_dataset_v2 will automatically become public, so that anyone can start using year 2018
-	After another year Jane creates a new version, sample_dataset_v5, including 2021 (private).
-	Sample_dataset_v3 will automatically become public, so that anyone can start using data until 2019
-	And so on…

**Comment by mdlux** [comment]
Consider also:
- once a dataset version is set to public (by the owner or at embargo end), it should be permanently public, so that whenever is cited by someone (ie: in a publication), it will be always possible to access it and visualize it
- in the web interface, when a dataset is selected, it will always default to the latest accessible version

**Comment by frafra** [comment]
Access key can be used to access to private resources.

The workflow should be properly documented.

**Comment by frafra** [comment]
Merged into #84.

**Comment by mdlux** [comment]
The workflow described in issue description is wrong. Embargo datasets need to be public, not private. Simply, the data files will not be downloadable, until the embardo end date. A user need to refer to the non-embargo version to be able to download data.
