### ISSUE TITLE
Contact Person - pick from a controlled vocabulary?

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#67]
Should also contact persons be picked from a controlled vocabulary, similarly to locations, tags, etc? Are contact persons always members of the COAT project, or could also be external?

**Comment by janeuhd** [comment]
There will be (a few) datasets with contact persons who have no need for a member account in the portal. But if it is possible to add a few names to the controlled vocabulary when that situation arrives, then a controlled vocabulary is a good idea to avoid variable spelling + mistakes. All the current members/editors can certainly be added.

**Comment by mdlux** [comment]
Hi @janeuhd ,
after some brainstorming about this with @frafra , we (administrators) would prefer to keep the full control over the process. Store a controlled vocabulary of contact persons, and update the list whenever a new one needs to be added. so we can keep it clean and standard, also for citation purposes, see #62 . Adding a new record to the list is easy (same as for keywords).

**Comment by janeuhd** [comment]
That is fine! All current editors/members can be added for now. Closing.

**Comment by mdlux** [comment]
@janeuhd : Are there already any names to be added to the list? 
 P.S: if an issue relates to some work we need to do, better to keep it open until it's implemented. It helps us have an overview of the TODOs. Reopening

**Comment by mdlux** [comment]
P.S: if an issue relates to some work we need to do, better to keep it open until it's implemented. It helps us have an overview of the TODOs. Reopening

**Comment by janeuhd** [comment]
OK. Sorry.
No, at present just add all current members and editors.

**Comment by frafra** [comment]
I added all the current members. Names could be shortened for references/citations.

**Comment by mdlux** [comment]
Now it defaults to the first person in alfabetical order. Should we default to something else? "Select a name", for example?

**Comment by janeuhd** [comment]
Yes, I think it would be better with default "Select a name".

**Comment by frafra** [comment]
Fixed.
