### ISSUE TITLE
Update explanation for "What is a dataset"

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#68]
I suggest added a bit more detail to the explanation of "What is a dataset?":

"A dataset is a collection of data resources (such as files), which can all be represented by the same set of metadata. Datasets are placed at a fixed URL, and are what users see when searching for data. A typical COAT dataset could be X number of files containing measurements of the same variable in X number of years. In addition, a coordinate file with sampling coordinates is mandatory for all plot-based datasets. Non-mandatory files, for instance containing plot or site levels environmental variables, or species lists, can be included in datasets when needed."

**Comment by frafra** [comment]
Fixed.
