### ISSUE TITLE
Monitor the number of downloads of public datasets?

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#69]
@frafra @mdlux 
Does CKAN have functionality for monitoring the number of downloads/requests of public datasets? I've found functionality for highlighting "most popular", but that seems to be based on page view tracking. That might be interesting to monitor as well, but the actual number of data requests made to the portal is probably more closely related to use, and it would be an important "use measure" to report from COAT over time.

**Comment by mdlux** [comment]
Hi Jane, we could extend the current tracking functions to include downloads and more. We will look into this and come back with more feedback.

**Comment by frafra** [comment]
Implemented.

**Comment by frafra** [comment]
Hi Jane,
when a user downloads a resource, a `downloads` field gets incremented and it is shown as metadata of the resource.

I see that this is not happening with the version running on the coatdemo server. I will fix it.

**Comment by frafra** [comment]
The issue has been fixed. The `downloads` field is empt if the resource has not been downloaded yet, while a number is displayed when the resource has already been download.
The counters on coatdemo consider downloads happened after 16:40 PM of today only.

**Comment by janeuhd** [comment]
I'm not sure this works as it should. I tried downloading the entire dummy dataset (e.g. the zip file) 3 times. There is no counter on the dataset as a whole, but I see that there is a counter on the individual resources. These however, does not seem to be updated in response to downloading the entire dataset, only when I download (or view) the individual resources? I think the most meaningful statistics to monitor is the number of times an entire dataset has been downloaded if this is possible? If this is not possible, an alternative might be a "total" count per dataset (e.g. the number of times one or more resources from a dataset has been downloaded). But in reality I think people will tend to download entire datasets rather than single resources.

**Comment by frafra** [comment]
I will add a counter for the dataset zip download too. In that case, do you think it is better to increment the downloads field of each resource every time the dataset as a whole is downloaded?

**Comment by janeuhd** [comment]
The most "correct" statistics would be if the counter on the zip file is incremented only when the entire zip is downloaded, while the counters on individual resources are incremented both when the zip file is downloaded and when they are downloaded individually.

**Comment by frafra** [comment]
Ok, thank you Jane. I implemented it and it is available on coatdemo.

**Comment by janeuhd** [comment]
Looks good! Closing this now.

**Comment by mdlux** [comment]
Be aware that a click on a txt resource, which creates an embedded visualization of the data in the resource detail view, is counted as a download
