### ISSUE TITLE
COAT data management plan

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#73]
First draft of the plan has been made by Jane and placed on Box: https://app.box.com/folder/96551847217

TODO @mdlux : add missing technical sections
TODO @mdlux and @frafra: make separate tab/container on data portal for storing the DMP. Latest version is public. Change log is kept in the document. 
TODO @janeuhd : Finish the draft and circulate to a few non-authors for comments before releasing v1

Deadline for release of v1 is Jan 31st 2020.

**Comment by janeuhd** [comment]
The DMP is now updated with all changes accepted and a clean version uploaded to Box. I have send this version to TT for quality check.  I’ll also circulate this version of the DMP to all module leaders as it is.
https://app.box.com/folder/96551847217

@mdlux @frafra  I’ve made a few edits:
-	I’ve added a link to non-existing repository on the github for storing study protocols. I think it makes sense to store the protocols here (will mostly be PDFs)? If you agree, we can add this repository.
-	In Annex A the automatically filled field Resource citation: the citation added started with the email address, not the name of the contact person. I don’t know if that is a typing error in the Annex or if it is an error in filling the field? The same error exists in the dummy data online. The resource citation have to start with the contact person’s last name.
- We need a container/tab on the portal for storing the DMP (public only most recent version, but we would want to keep also older versions). Which is the best solution for this? 
https://github.com/COATnor/COAT_portal_issues/issues/73#issue-540863479

**Comment by frafra** [comment]
- I would suggest against storing PDF or others binary files in GitHub. I would suggest instead using [Markdown ](https://guides.github.com/features/mastering-markdown/) files, which are lightweight, human-readable (like txt) thus GitHub can shows diff between version and provide a better workflow, instead of having multiple PDF files with different names for different versions stored on GitHub (if that is really what we want, it would be better to use a different platform, like a shared folder on Sharepoint).
- It will be fixed in the final deployment
- As general way to handle documents, I would propose to use/modify the "About" page and add links to GitHub repository containing Markdown files or Sharepoint read-only shared folders handled by NINA containing PDFs

**Comment by janeuhd** [comment]
I think I would prefer to keep the DMP in Word->export to PDF. The same goes for the study protocols (for which we have made a - so far empty - repository in github). They are all in word/PDF and I'm sure that is how people would like to keep them simply because that is what they are used to. markdown I think will be a barrier to some. Over time this may change, but not within the time frame we have to provide a first operational version of the portal. 

For the DMP I agree that modifying the About page in the portal and providing a link there to the most recent version of the DMP is sufficient. Placing it on a sharepoint should be fine.

For the protocols I'm not sure. We need to be able to link to them from the metadata. Can this be done if they are placed in a sharepoint? @frafra

**Comment by frafra** [comment]
It can be done, but we though about a different alternative: have a special dataset type for protocols, like we did for state variables, so everything is stored in the same platform. [PDF/A](https://en.wikipedia.org/wiki/PDF/A) can be stored in COAT, while the Word files could be kept in a NINA Sharepoint project folder.

**Comment by janeuhd** [comment]
That would make sense. Let's do that.

**Comment by frafra** [comment]
We have implemented a hidden "dmp" dataset type just for the DMP, which can be reached from the About page for now.
