### ISSUE TITLE
"Addional info" field are not updated in response to changes in metadata

### ISSUE THREAD

**Issue by janeuhd** [COATnor/COAT_portal_issues#76]
There seems to be a bug in the update of the metadata fields visible under Additional info under data sets. Here:
![image](https://user-images.githubusercontent.com/35291431/72430292-40cab200-3792-11ea-8fbc-f2fb059c84b8.png)

I made some changes in the metadata of the dummydata v2. They are not visible in additional info. I also tried to make a new version (v3) of the dataset. They are not visible here either.

**Comment by frafra** [comment]
Hi Jane,
what field have you tried to change? I did multiple changes on all the fields of that dataset but I did not encounter any problem. Could you please give more details about this issue?

**Comment by janeuhd** [comment]
I tested this on the dummy dataset (private versions v2 and v3). tried just a few fields (email contact person, associated parties/persons).  In v2 I clicked "manage" and I added an email address for the contact person and an associated party. They are visible if I go back into "manage", but they are not updated in the "Additional information". That means that nobody from outside can see those changes. I then made a new version (v3). Also in v3 they are only visible if I go into manage.

**Comment by frafra** [comment]
Unable to replicate here. Could you please try again?
Do you click on "Update Dataset" as usual after changing the value of the fields? Have you tried to refresh the web page (press F5)?

**Comment by janeuhd** [comment]
This is very strange. When I tried last time (+ earlier today) I could not update any of the (few) fields I tried. I tried both Update and F5. When I try now I'm able to update all fields except email address. I've tried deleting the address in there, updating, adding a new one, updating, but the field remains empty in Additional info.

**Comment by frafra** [comment]
The "email" field seems to have a different issue.

The strange behaviour you have seen could be due to a networking issue we are investigating with datahjelp.

**Comment by frafra** [comment]
"email" field bug has been fixed.
