### ISSUE TITLE
New dataset type: protocols

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#80]
It can be done, but we though about a different alternative: have a special dataset type for protocols, like we did for state variables, so everything is stored in the same platform. [PDF/A](https://en.wikipedia.org/wiki/PDF/A) can be stored in COAT, while the Word files could be kept in a NINA Sharepoint project folder.

_Originally posted by @frafra in https://github.com/COATnor/COAT_portal_issues/issues/73#issuecomment-588131858_

**Comment by frafra** [comment]
@janeuhd is any specific metadata required for protocols? Should a multiple selection field be added to the state variables metadata?

**Comment by janeuhd** [comment]
No I don't think the protocols need specific metadata. They just need a storage container, so we can link to them from the **data set** metadata.
Yes, it would be practical if the **data set** metadata  field for 'protocol' could be multiple choice, to avoid people choosing a protocol which do not exist.

**Comment by frafra** [comment]
- [ ] Add custom description
- [ ] Add a button on the main navbar
- [ ] Datasets should have a dropdown to select the related protocol

**Comment by eevasoininen** [comment]
Custom description could be: "COAT protocol includes a common part describing the study design, and a set of data collection protocols. Protocols are pdf-files placed at a fixed URL, and are what users see when searching for data. Protocols do not include metadata."

**Comment by frafra** [comment]
Done and deployed, both in testing and production.

**Comment by janeuhd** [comment]
@frafra 
When uploading a protocol the legend on the page is the same as for adding a dataset (e.g. 1. Create dataset, 2. Add data). Also the path displayed above the "What are protocols is Datasets/Create datasets". I find that confusing and I suspect others will as well. Could we override that so that is shows Protocols/Create protocol etc? It has been done for Modules, but not for protocols and state variables.

![image](https://user-images.githubusercontent.com/35291431/85013748-6145d080-b165-11ea-8e42-651cfb67b78a.png)

**Comment by frafra** [comment]
It looks fine to me on both https://data.coat.no (production) and https://coatdemo.nina.no (testing). Could it be that you are looking at the old test instance on coatdemo.frafra.no?

**Comment by janeuhd** [comment]
No I'm on coatdemo.nina.no. Try clicking Add state variable or Add Protocol. It has not been corrected there.

**Comment by frafra** [comment]
Oh, I am sorry Jane, I see what you mean. Let me see how it can be fixed.

**Comment by frafra** [comment]
It is not trivial to fix that, it requires a major change, so I opened a bug upstream: https://github.com/ckan/ckan/issues/5451

In the meanwhile I changed the two labels to improve consistency.
