### ISSUE TITLE
Assign explicitly a global unique identifier to each dataset

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#81]
To be FAIR, two points of the "findability" need to be addressed:

F1. (Meta)data are assigned a globally unique and persistent identifier
and
F3. Metadata clearly and explicitly include the identifier of the data they describe

**Comment by mdlux** [comment]
It was decided to use DOIs.

**Comment by mdlux** [comment]
To all Research and data leaders:

I assume that both datasets and State Variables should have a DOI.

Also, DOIs will be created for each resource (file) added to a dataset/State variable.

Being protocols a specialized kind of dataset (from a technical point of view), they would also be assigned a DOI, unless we modify the basic behavior. Should protocols be excluded from getting a DOI?

**Comment by frafra** [comment]
DOIs are now generated and displayed on coatdemo.

**Comment by frafra** [comment]
Test DOIs are now generated on coatdemo.

**Comment by mdlux** [comment]
@janeuhd Hei Jane, do you think DOIs for both datasets and State variables? We will assume that. Or, For state variables not?

**Comment by janeuhd** [comment]
@mdlux for both I would say.

**Comment by mdlux** [comment]
Ok, thanks
