### ISSUE TITLE
State variables description

### ISSUE THREAD

**Issue by frafra** [COATnor/COAT_portal_issues#85]
State variables description is missing at the moment. Which text should we use?

**Comment by janeuhd** [comment]
Suggestion for "What are.." texts for datasets, state variables, protocols and modules below.

What are datasets?
A dataset is a collection of data resources (such as files), which can all be represented by the same set of metadata. Datasets are placed at a fixed URL, and are what users see when searching for data. A typical COAT dataset could be X number of files containing measurements of the same variable in X number of years. In addition, a coordinate file with sampling coordinates is mandatory for all plot-based datasets. Non-mandatory files, for instance containing plot or site levels environmental variables, or species lists, can be included in datasets when needed.

What are state variables?
A state variable describes directly a feature related to the state of the ecosystem. Such features can be related to ecosystem functions, or structure and processes. State variables are calculated based on biotic or climatic datasets from COAT, and contain metadata fields which link directly both to the underlying datasets and the scripts documenting how the state variable has been calculated from the datasets. 

What are protocols?
COAT study protocol includes a common part describing the study design, and a set of data collection protocols. Protocols are pdf-files placed at a fixed URL. COAT datasets contain a metadata field which link to the relevant protocol describing the study design and collection of the data. Protocols do not include separate metadata.

What are modules?
The monitoring activity in COAT is organized into food web modules. Each of the food web modules includes a subsets of strongly linked species (or functional groups/species assemblages) that have high climate sensitivity and key functions. Key functions can be either ecological and/or societal. Each module is named by one of it’s primary monitoring targets - often the one with the highest management relevance.

**Comment by frafra** [comment]
All the text descriptions have been updated, thanks.
