### ISSUE TITLE
broken link when creating new version of a link-only dataset

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#86]
If a dataset has no resource data, but only a link, when a new version of the dataset is created the link  is wrong, and defaults to http://+[resource title]

**Comment by frafra** [comment]
Not urgent in my opinion, as this does not affect COAT dataset.

**Comment by frafra** [comment]
Code fixed in the `ckanext-coat` module.

**Comment by frafra** [comment]
Deployed.
