### ISSUE TITLE
https://coatdemo.coat.no/ not available

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#89]
Cannot open https://coatdemo.coat.no/; message "web page not available"

**Comment by mdlux** [comment]
Current Demo available at https://coatdemo.nina.no/
It will be renamed to https://coatdemo.coat.no/, and temporarily solved with a redirect.

**Comment by mdlux** [comment]
The current Demo is available at https://coatdemo.coat.no/
