### ISSUE TITLE
file extensions shouldn't be case sensitive

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#9]
When adding a file to a dataset and choosing the file extension: the file extension seems to be case sensitive, could this be removed? If for example I upload two files and for one I wrote .txt and for the other .TXT, then they are handled as two different formats (and on the filterlist of formats both show up).

**Comment by frafra** [comment]
I can make all the resources with their extension lowercase when created.

**Comment by frafra** [comment]
Extensions are transformed to lowercase and conflicts checks are case-insensitive.
