### ISSUE TITLE
https://data.coat.no/organization lacks modules (with logos) that used to be available in the demo portal

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#90]
https://data.coat.no/organization lacks modules (with logos) that used to be available in the demo portal

**Comment by frafra** [comment]
Everything has been recreated (not by me actually), except for the cross-dataset module. I am not sure if that is needed, but I saved it on my PC just for safety.

**Comment by frafra** [comment]
Sorry if I closed that too soon. Modules are there, logos are not due to an error of an external program I just reported: https://github.com/ckan/ckanapi/issues/160

**Comment by janeuhd** [comment]
OK. If this is something that takes time to fix, then I assume I can upload the logos manually to have them in place for the application deadline?

**Comment by frafra** [comment]
I fixed the external tool and proposed the patch to be included in the external software, as we usually do when improving opensource software.

Pictures have been uploaded using our improved version.
