### ISSUE TITLE
Protocols listed as datasets

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#93]
So far, all protocols are listed and counted as datasets in the dataset menue (if you click on 'Datasets'). Is it possible that the protocols will be only listed under 'Protocols'?

Furthermore, the 'COAT Data Portal statistics' on the start page says that there are 5 datasets. However, there are 4 datasets and 3 protocols as far as I see. Not sure if I don't understand the statistics of if there is an error.

**Comment by frafra** [comment]
@hannaboe Sure! But this would be a backward incompatible change, and we would need to find a different name for datasets.
The software relies on the fact that "datasets" are *all* the datasets (including protocols and state variables). Is there any term we can use for datasets that are just datasets?

**Comment by frafra** [comment]
It looks like we could avoid finding a different name for standard datasets and avoiding compatibility breaks: https://github.com/ckan/ckan/issues/4898

**Comment by frafra** [comment]
Fixed in code, will be deployed with the next update.

**Comment by frafra** [comment]
The fix has been deployed.
